// HerramientasBuildSystemsYTecnologíasEmergentes/src/app/login/login.component.ts
import { Component } from '@angular/core';
import { HttpService } from './../http.service';
import { Response } from '@angular/http';
import { Router } from "@angular/router";

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {

  constructor(private httpService : HttpService, private router: Router) { }

  login(){
  	let email = ((document.getElementById("email") as HTMLInputElement).value),
  		pass = ((document.getElementById("password") as HTMLInputElement).value);

  	if(email !== '' && pass !== ''){
  		this.checkLogin(email, pass);
  	}
  }

  	checkLogin(email: string, password: string){
  		let usuario = [];
  		usuario['email'] = email;
  		usuario['password'] = password;

  		return this.httpService.getDatos()
  			.subscribe(
  				(data: Response) => {
  					for(let i = 0, j = data['users'].length; i < j; i++){
  						let flag = false;

  						if(usuario['email'] == data['users'][i].email && usuario['password'] == data['users'][i].password){
  							flag = true;
  						}

  						if(flag){
  							this.router.navigate(['/panel'])
  						}else{
  							document.getElementById('errorMsg').innerHTML = 'Error en el acceso, intenta nuevamente';
  						}
  					}
  				}
  			);
  	}
}

<div id="main">
	<div class="bg-fix s_centered row">
		<div class="box col s8 m6 l4 pull-s2 pull-m3 pull-l4">
			<h5 class="title">Inicia sesión</h5>
			<form action="" class="col s12 m12">
				<div class="row input-field col s12 m12 l12">
					<label for="email">Correo electrónico</label>
					<input id="email" type="email" class="validate" required>
				</div>
				<div class="row input-field col s12 m12 l12">
					<label for="password">Contraseña</label>
					<input id="password" type="password" class="validate" required>
				</div>
				<div class="row">
					<div id="errorMsg" class="col s12 m12 l12"></div>
				</div>
				<div class="btn-area">
					<input type="submit" (click)="login()" class="waves-effect waves-light btn" value="Ingresar">
				</div>
			</form>
		</div>
	</div>
</div>

// Versión React/login.jsx
import React from 'react';
import firebase from 'firebase';
import { Redirect } from 'react-router-dom'

class Login extends React.Component{
	constructor(){
		super()

        // This binding is necessary to make `this` work in the callback
        this.handleLogin = this.handleLogin.bind(this);

        this.state = {
            redirect: false
        }

        /*const database = firebase.database(),
              ref_users = database.ref('users');

        var q = database.ref().child('test').child('name');

        q.on('value', (snapshot) => {
            console.log(snapshot.val());
        })*/
	}

    renderRedirect(){
        if(this.state.redirect){
            return <Redirect to='panel' />
        }
    }

    handleLogin(e){
        e.preventDefault();
        const database = firebase.database(),
              ref_users = database.ref('users');

        var email = document.getElementById('email').value,
            password = document.getElementById('password').value;

        ref_users.once('value', (snapshot) => {
            const users = snapshot.val();
            let flag = false;

            for(let i = 0, j = users.length; i < j; i++){
                if(email == users[i].email){
                    if(password == users[i].password){
                        flag = true;
                    }else{
                        console.log('Esa no es la contraseña, china tu maye');
                    }
                }
            }

            if(flag){
                this.setState({redirect: true})
            }else{
                document.getElementById('errorMsg').innerText = 'Error vuelve a intentarlo';
            }
        })
    }

    render(){
        return(
            <div>
                {this.renderRedirect()}
                <div id="main">
                    <div className="bg-fix s_centered row">
                        <div className="box col s8 m6 l4 pull-s2 pull-m3 pull-l4">
                            <h5 className="title">Inicia sesión</h5>
                            <form className="col s12 m12">
                                <div className="row input-field col s12 m12 l12">
                                    <label htmlFor="email">Correo electrónico</label>
                                    <input id="email" type="email" className="validate" name="email" required/>
                                </div>
                                <div className="row input-field col s12 m12 l12">
                                    <label htmlFor="password">Contraseña</label>
                                    <input id="password" type="password" className="validate" name="password" required/>
                                </div>
                                <div className="row">
                                    <div id="errorMsg" className="col s12 m12 l12"></div>
                                </div>
                                <div className="btn-area">
                                    <input type="submit" onClick={this.handleLogin} className="waves-effect waves-light btn" value="Ingresar"/>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        );
    }
}

export default Login;
